### ISSUE TITLE
Data in annotation_3d is missed [Bug]

### ISSUE THREAD

**Issue by icicle4** [longcw/crossview_3d_pose_tracking#14]
The dataset's annotation_3d pose_3d num is not equal to the num in multiview images. Would you please tell me wheather it is a bug or not?

Like below:

![image](https://github.com/longcw/crossview_3d_pose_tracking/assets/31507380/db788975-d417-4fd3-a5ad-bd79945e4f13)
![image](https://github.com/longcw/crossview_3d_pose_tracking/assets/31507380/ca12b977-1d6f-41da-90fa-437780b4cb4a)

**Comment by longcw** [comment]
@icicle4 Can you provide the timestamps of your examples? You may also want to check the raw data from Campus: https://www.epfl.ch/labs/cvlab/data/data-pom-index-php/ and Shelf: http://campar.in.tum.de/Chair/MultiHumanPose, at least in your second example the visualization is expected since that person was not annotated in the dataset.
<img width="358" alt="image" src="https://github.com/longcw/crossview_3d_pose_tracking/assets/6198400/5949b05d-f656-4c57-9167-b3406a7208a1">

**Comment by icicle4** [comment]
> @icicle4 Can you provide the timestamps of your examples? You may also want to check the raw data from Campus: https://www.epfl.ch/labs/cvlab/data/data-pom-index-php/ and Shelf: http://campar.in.tum.de/Chair/MultiHumanPose, at least in your second example the visualization is expected since that person was not annotated in the dataset. <img alt="image" width="358" src="https://user-images.githubusercontent.com/6198400/267010264-5949b05d-f656-4c57-9167-b3406a7208a1.png">

The first timesteps is 120.0 for Shelf dataset. As you can see, there is only one id.
![image](https://github.com/longcw/crossview_3d_pose_tracking/assets/31507380/196e501b-f8de-4343-82cf-81baf74fac2a)

For the second example, you are right. The original dataset only provide the three people's 3d poses.
